#!/bin/bash
set -euxo pipefail

# URL of the web application
URL="http://heroku-ubuntu:5001"

# Check if the web app is responding
if curl -s --head "$URL" | grep "200 OK" > /dev/null; then
    echo "Web app is responding."
else
    fail-message "Web app is not responding."
fi