version: "3"
containers:
- name: heroku-account
  image: gcr.io/instruqt/virtual-browser:prod
  ports:
  - 9000
  environment:
    url: https://dashboard.heroku.com/account/applications
  memory: 4096
  resources:
    memory: 4096
virtualmachines:
- name: heroku-ubuntu
  image: ubuntu-os-cloud/ubuntu-2204-lts
  memory: 4096
  cpus: 1
